// what to do with the hoursObject once it's been built
function processHours(data, tabletop) {
    // get page_date however you want, I'm just defaulting to new Date
    var date = new Date(2015, 11, 31);

    // build the hours object
    var libhoursObject = new window.libhours(data, date);

    // get all hours
    var completeHoursObject = libhoursObject.getCompleteHoursObject();

    console.log(completeHoursObject);

    // get just one day of hours for one lib
    var singleHoursObject = libhoursObject.getSingleHoursObject(date, 'Barker Library')

    console.log(singleHoursObject);
}

window.onload = function() {
    // call this when you are ready to get the data and use it
    Tabletop.init({
        // key is generated by Google doc
        key: '1aEV-CZIqJD9hHJWNWTWIN0I4Cgz3M8jpl4hQwA9l8JU',

        // location of hard-coded json files (not sure where they'll be stored yet)
        proxy: "http://libraries-dev.mit.edu/app/libhours-buildjson/",

        // function to call when the data is retrieved
        callback: processHours,

        simpleSheet: false
    });
}